## Default configuration for the Prospector Extension.
# Prospector builds combine with *_dongle shields that default ZMK display off.
CONFIG_ZMK_DISPLAY=y
CONFIG_DISPLAY=y
CONFIG_LVGL=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=n
CONFIG_SSD1306=n
CONFIG_LV_COLOR_DEPTH_16=y
CONFIG_LV_Z_BITS_PER_PIXEL=16

CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=100
# CONFIG_PROSPECTOR_ROTATE_DISPLAY_180=n

# ## Prospector New Status Screens
# Use one of the following to enable a new status screen. Only one can be enabled at a time.
# CONFIG_PROSPECTOR_STATUS_SCREEN_RADII=y
# CONFIG_PROSPECTOR_STATUS_SCREEN_FIELD=y
CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y

# ## Prospector New Status Screens - Additional Options
# CONFIG_PROSPECTOR_ROTATE_DISPLAY_180=n
# CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=y
# CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=50
# CONFIG_PROSPECTOR_LAYER_NAME_UPPERCASE=y
# CONFIG_PROSPECTOR_SHOW_MODIFIERS=y
# CONFIG_PROSPECTOR_SHOW_INACTIVE_MODIFIERS=y
# CONFIG_PROSPECTOR_MODIFIER_ORDER="GACS"
# CONFIG_PROSPECTOR_ANIMATION_WPM_REFERENCE=70
# CONFIG_PROSPECTOR_ANIMATION_INTENSITY_DECAY_SEC=30
# CONFIG_PROSPECTOR_ANIMATION_FLOW_DECAY_SEC=300

