name: Draw Keymap
on:
  workflow_dispatch:
  push:
    paths:
      - "config/eyelash_corne.keymap"
      - "config/*.dtsi"
      - "keymap-drawer/config.yaml"
      - ".github/workflows/draw.yml"

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      commit_message: "[Draw] ${{ github.event.head_commit.message }}"
      destination: "commit"
      fail_on_error: ${{ fromJSON(true) }}
